### ISSUE TITLE
why border-left matters?

### ISSUE THREAD

**Issue by uniquejava** [eCollect/vue-swipe-actions#8]
Hello, thank you for this great vue component.
I met an issue today. I'd like to move the list border in your example from on swipe-list to swipe-list-item and the swipe does not work any longer, the actions to be revealed always bounced back on mouse release.

This is the css style I used.
```css
.swipeout-list-item {
  flex: 1;
  margin: 0.5em;
  border: 1px solid lightgray; // I added some border here
  border-radius: 10px;
}
.card {
  width: 100%;
  background-color: white;
  // removed the border here.
}
.card-content {
  padding: 1rem;
}
```

![image](https://user-images.githubusercontent.com/1049271/49203801-8dafc580-f3e4-11e8-8b13-3839418c7601.png)

Any clue why it is not working and how to fix it.  Appreciate your help. Thank you.
